In [43]:
import numpy as np

print("Input:")
N = int(input())                            #배열의 크기 입력
 
A = np.random.random((N,N))                 #랜덤 배열 생성
result = []
for i in range(0,N,2):                      #2x2배열로 나눠서
    for j in range(0,N,2):
        max = A[i][j]                       #최댓값 초기 설정
        if(A[i][j+1] > max):                #최댓값 찾기
            max = A[i][j+1]
        if(A[i+1][j] > max):
            max = A[i+1][j]
        if(A[i+1][j+1] > max):
            max = A[i+1][j+1]
        result.append(max)
B = np.array(result)                        #결과값이 든 리스트를 배열로 변경
B = B.reshape(N//2,N//2)                    #2x2 배열로 바꾸기

print()
print("Output:")
print(A)
print(B)

Input:
4

Output:
[[0.46772236 0.17930466 0.94663472 0.34083162]
 [0.67271421 0.76453423 0.74819081 0.95758647]
 [0.40119959 0.84839029 0.50978226 0.08738787]
 [0.05871379 0.26180012 0.34327841 0.34878237]]
[[0.76453423 0.95758647]
 [0.84839029 0.50978226]]
